carbon-design-system/gatsby-theme-carbon

packages/example/src/data/nav-items.yaml
packages/example/src/pages/component-examples/Caption.mdx
packages/example/src/pages/component-examples/ImageComponent.mdx
packages/example/src/pages/component-examples/demo.mdx
packages/gatsby-theme-carbon/index.js
packages/gatsby-theme-carbon/src/components/Caption/Caption.js
packages/gatsby-theme-carbon/src/components/Caption/caption.scss
packages/gatsby-theme-carbon/src/components/Caption/index.js
packages/gatsby-theme-carbon/src/styles/_page.scss
packages/gatsby-theme-carbon/src/styles/index.scss

feat: caption

---

packages/example/src/data/nav-items.yaml
packages/example/src/pages/top-level-with-tabs/tab-one.mdx
packages/example/src/pages/top-level-with-tabs/tab-two.mdx
packages/gatsby-theme-carbon/src/components/LeftNav/LeftNavItem.js
packages/gatsby-theme-carbon/src/components/LeftNav/LeftNavItem.module.scss
packages/gatsby-theme-carbon/src/components/NextPrevious/NextPrevious.js

Top level with tabs

---

packages/example/src/pages/components/ResourceCard.mdx

- add basic `<ResourceCard>` docs

chore(ResourceCard): add ResourceCard docs

---

packages/example/src/pages/components/Aside.mdx

- add basic docs for `<Aside>` component

chore(aside): add aside docs

---

packages/example/src/pages/components/Caption.mdx

- Add basic docs for `<Caption>` component

chore(caption): add caption docs

---

packages/example/src/pages/components/DoDontExample.mdx
packages/example/src/pages/components/demo.mdx
packages/gatsby-theme-carbon/src/components/DoDontExample/DoDontExample.js
packages/gatsby-theme-carbon/src/components/DoDontExample/do-dont-example.scss

- Add docs for `<DoDontExample>`
- Refactor propTypes
| old prop      | new prop            |
| ------------- | ------------------- |
| `correct`     | `type="do"`         |
| `square`      | `aspectRatio="1:1"` |
| `dark`        | `color="dark`       |
| `label`       | `caption`           |
| `description` | `captionTitle`      |

feat(doDontExample): refactor component, add docs

---

packages/gatsby-theme-carbon/src/components/Code/Code.js
packages/gatsby-theme-carbon/src/components/Code/_code.scss

fixes grid alignment for code snippet

feat(code): grid fix

---

packages/gatsby-theme-carbon/src/styles/index.scss

fix: re-order sass imports

---

packages/gatsby-theme-carbon/src/components/Footer.js
packages/gatsby-theme-carbon/src/components/Homepage/homepage.scss
packages/gatsby-theme-carbon/src/components/NextPrevious/NextPrevious.module.scss
packages/gatsby-theme-carbon/src/components/NextPrevious/NextPreviousStyles.js
packages/gatsby-theme-carbon/src/components/PageHeader/PageHeader.js
packages/gatsby-theme-carbon/src/components/PageHeader/PageHeader.module.scss

fix: properly align Footer and NextPrevious with content

---

packages/example/src/pages/components/ArticleCard.mdx
packages/example/src/pages/components/FeatureCard.mdx
packages/example/src/pages/components/ResourceCard.mdx
packages/gatsby-theme-carbon/src/components/ArticleCard/ArticleCard.js
packages/gatsby-theme-carbon/src/components/ArticleCard/article-card.scss
packages/gatsby-theme-carbon/src/components/FeatureCard/FeatureCard.js
packages/gatsby-theme-carbon/src/components/FeatureCard/feature-card.scss
packages/gatsby-theme-carbon/src/components/ResourceCard/ResourceCard.js
packages/gatsby-theme-carbon/src/components/ResourceCard/resource-card-group.scss

- feat(ArticleCard): add subtitle prop closes #107 
- feat: add email icon option to all cards closes #103  (will need to add to ImageCard once that gets merged in)
- fix(ResourceCard): mobile border styles, resource-card-group closes #100 
- fix(featureCard): fix grid alignment for feature card

feat: card enhancements

---

packages/gatsby-theme-carbon/src/components/markdown/H4.js
packages/gatsby-theme-carbon/src/components/markdown/H5.js
packages/gatsby-theme-carbon/src/components/markdown/H6.js
packages/gatsby-theme-carbon/src/components/markdown/Ol.js
packages/gatsby-theme-carbon/src/components/markdown/Ul.js

fix: Adjust header margins and list styles

---

packages/example/src/data/nav-items.yaml
packages/example/src/pages/components/Tabs.mdx
packages/gatsby-theme-carbon/index.js
packages/gatsby-theme-carbon/src/components/Tabs/Tabs.js
packages/gatsby-theme-carbon/src/components/Tabs/Tabs.module.scss
packages/gatsby-theme-carbon/src/components/Tabs/index.js
packages/gatsby-theme-carbon/src/components/markdown/Ol.js
packages/gatsby-theme-carbon/src/components/markdown/Ul.js

feat: Add Tabs component

---

packages/gatsby-theme-carbon/src/components/LeftNav/LeftNavWrapper.js

fix: allow scrolling sidenav

---

packages/gatsby-theme-carbon/src/components/LeftNav/LeftNavItem.js

fix: update active state logic for tabs

---

packages/gatsby-theme-carbon/src/components/DoDontExample/do-dont-example.scss
packages/gatsby-theme-carbon/src/components/Tabs/Tabs.module.scss

fix: update margin bottom for do-dont and tabs

---

packages/gatsby-theme-carbon/src/components/Switcher/Switcher.js

chore: update switcher link for design

---

packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss

Updates list width to responsive width.

fix: list width

---

packages/example/src/pages/getting-started/index.mdx

Edited the intro paragraph on Getting started to use more direct and punchy language.

docs(getting-started): Punchier intro paragraph

---

packages/example/src/gatsby-theme-carbon/components/Footer.js
packages/gatsby-theme-carbon/src/components/Footer/Footer.js
packages/gatsby-theme-carbon/src/components/Footer/Footer.module.scss
packages/gatsby-theme-carbon/src/components/Footer/index.js

closes #200 
converts Footer component to css modules
pulls in correct styling from spec

feat: refactor Footer to css modules with correct styling

---

packages/gatsby-theme-carbon/src/components/Switcher/Switcher.js

Related to https://github.com/IBM-Design/design-website/pull/386

fix: update switcher link for Enterprise Design Thinking

---

packages/gatsby-theme-carbon/src/components/FeatureCard/feature-card.scss

fix: feature cards at max width

---

packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss

Related to https://github.com/carbon-design-system/design-language-website/pull/139 and #136

fix: update type token for blockquote to be responsive

---

packages/gatsby-theme-carbon/src/components/AutolinkHeader/AutolinkHeader.module.scss

fix(autolinkheader): no hover icon on small screens

---

packages/example/src/pages/components/Aside.mdx
packages/gatsby-theme-carbon/src/components/Aside/Aside.module.scss

ref https://github.com/carbon-design-system/design-language-website/pull/139
matches aside spacing to live IDL site. Updates example column width to match IDL also.

fix: remove extra spacing in aside component

---

packages/gatsby-theme-carbon/src/components/Homepage/Callout.module.scss

fix: update callout header to expressive heading 03

---

packages/gatsby-theme-carbon/src/styles/internal/_website-side-nav.scss

closes #337 
I broke stuff, this fixes it

fix: add right border back to nav on dark

---

packages/example/src/pages/components/ArtDirection/index.mdx

ref #https://github.com/carbon-design-system/carbon-website/issues/224

fix: typo on art direction component page

---

packages/example/src/pages/gallery/index.mdx

fix: broken link on gallery page for IDL

---

packages/gatsby-theme-carbon/src/styles/internal/_global.scss

feat: enable carbon custom properties

---

packages/example/src/data/nav-items.yaml

Closes #
**New**
**Changed**
**Removed**

docs: alpha components list

---

packages/example/src/pages/demo/index.mdx
packages/gatsby-theme-carbon/src/components/Main/Main.module.scss

fix: add margin-top to nested elements within columns

---

packages/gatsby-theme-carbon/config/lunr-options.js
packages/gatsby-theme-carbon/src/components/GlobalSearch/GlobalSearch.js

new: catch lunr search errors and remove problematic stemmer
Closes #523 
closes https://github.com/carbon-design-system/carbon-website/issues/585

fix: search explosion

---

packages/gatsby-theme-carbon/src/components/DoDontExample/do-dont-example.scss

Closes #499 
**Changed**
- dont color to red 60

fix(do-dont): update dont color

---

packages/example/src/pages/guides/configuration.mdx

Updated the link to the `frontmatter` section

fix:(Configuration page broken link)

---

packages/gatsby-theme-carbon/src/components/Header/Header.js
packages/gatsby-theme-carbon/src/components/LeftNav/LeftNav.js
packages/gatsby-theme-carbon/src/components/LeftNav/LeftNavItem.js
packages/gatsby-theme-carbon/src/components/LeftNav/ResourceLinks.js
packages/gatsby-theme-carbon/src/components/MDXProvider/defaultComponents.js
packages/gatsby-theme-carbon/src/components/markdown/Li.js
packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss
packages/gatsby-theme-carbon/src/components/markdown/Ol.js
packages/gatsby-theme-carbon/src/components/markdown/Ul.js
yarn.lock

fix: update carbon and patch list styles

---

packages/example/src/pages/components/Caption.mdx
packages/gatsby-theme-carbon/src/components/Caption/Caption.js
packages/gatsby-theme-carbon/src/components/Caption/Caption.module.scss
packages/gatsby-theme-carbon/src/styles/index.scss

Caption spacing fix

---

packages/gatsby-theme-carbon/src/components/Footer/Footer.module.scss

fix: update footer top spacing closes #327

---

.github/workflows/prerelease.yml

publishes to `next` on push to master

chore: use lerna for pre-release

---

.github/workflows/prerelease.yml

Closes #
**New**
**Changed**
**Removed**

chore: cd into theme package

---

.github/workflows/prerelease.yml

Closes #
**New**
**Changed**
**Removed**

chore: use npm

---

packages/gatsby-theme-carbon/src/components/NextPrevious/NextPrevious.module.scss
packages/gatsby-theme-carbon/src/components/NextPrevious/NextPreviousStyles.js

closes #730 
new: uses grid components for next/prev

fix: use grid for next-prev

---

packages/gatsby-theme-carbon/src/components/NextPrevious/NextPrevious.module.scss

fix: next-prev click target too small regression

---

.github/workflows/prerelease.yml

Closes #
**New**
**Changed**
**Removed**

chore: cache node_modules

---

packages/gatsby-theme-carbon/src/styles/internal/_plex.scss

Closes #
**New**
**Changed**
**Removed**

fix: other-subset group

---

packages/gatsby-theme-carbon/src/components/Switcher/Switcher.js

fix: useLayoutEffect to ensure switcher closed on initial render

---

packages/gatsby-theme-carbon/src/components/FourOhFour/FourOhFour.module.scss

Closes #829
Added some padding to the heading and removed margin from the container. Looks smooth as silk.

fix(404): header

---

packages/gatsby-theme-carbon/src/components/HeaderNav/HeaderNav.js
packages/gatsby-theme-carbon/src/components/HeaderNav/HeaderNavItem.js

Update import to carbon-components-react to use ESM entrypoint
**New**
**Changed**
- Update import to carbon-components-react to use ESM entrypoint
**Removed**

fix(header-nav): update import to carbon-components-react

---

lerna.json
packages/example/package.json
packages/gatsby-theme-carbon/package.json
packages/gatsby-theme-carbon/src/components/FeedbackDialog/Experience.js
packages/gatsby-theme-carbon/src/components/GlobalSearch/GlobalSearch.js
packages/gatsby-theme-carbon/src/components/Grid/Grid.js
packages/gatsby-theme-carbon/src/components/Grid/Grid.module.scss
packages/gatsby-theme-carbon/src/components/Grid/index.js

This adds a margin-bottom to columns when <lg breakpoint. It also moves the Grid into a folder so we might want to mention that in the release notes in case anyone is shadowing.

Column space

---

packages/gatsby-theme-carbon/src/components/Code/Code.module.scss

fix: copy label

---

packages/gatsby-theme-carbon/src/components/Video/Video.js

fix: test poster is not prefixed before prefixing

---

packages/example/src/pages/guides/styling.mdx
packages/gatsby-theme-carbon/src/components/BackToTopBtn/BackToTopBtn.module.scss
packages/gatsby-theme-carbon/src/components/Code/Code.module.scss
packages/gatsby-theme-carbon/src/components/FeedbackDialog/Form.module.scss
packages/gatsby-theme-carbon/src/components/GlobalSearch/GlobalSearch.module.scss
packages/gatsby-theme-carbon/src/components/Header/Header.module.scss
packages/gatsby-theme-carbon/src/components/LeftNav/LeftNavWrapper.module.scss
packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.module.scss
packages/gatsby-theme-carbon/src/styles/internal/_page.scss

fix: z-index changes upstream from carbon

---

package.json
packages/example/package.json
packages/gatsby-theme-carbon/package.json
yarn.lock

[manypkg](https://github.com/Thinkmill/manypkg) is a really cool tool that analyzes your workspace to find any potential discrepancies/issues in dependency versions.

chore: implement dependency recommendations from manypkg

---

packages/example/src/data/nav-items.yaml
packages/gatsby-theme-carbon/src/components/LeftNav/LeftNav.module.scss

DON'T MERGE UNTIL I REMOVE THE DIVIDER
;)

fix(divider): lines match on dark theme

---

packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss

Closes #663 
- no longer blue text (in both light and dark pages)
- removes quotes
- italicized text

fix: blockquote styles

---

packages/gatsby-theme-carbon/src/components/ArticleCard/article-card.scss

fix: article card title type

---

packages/gatsby-theme-carbon/src/components/BackToTopBtn/BackToTopBtn.module.scss
packages/gatsby-theme-carbon/src/components/FeedbackDialog/Checkmark.js
packages/gatsby-theme-carbon/src/components/FeedbackDialog/Checkmark.module.scss
packages/gatsby-theme-carbon/src/components/FeedbackDialog/FeedbackDialog.js
packages/gatsby-theme-carbon/src/components/FeedbackDialog/Form.js
packages/gatsby-theme-carbon/src/components/FeedbackDialog/Form.module.scss
packages/gatsby-theme-carbon/src/components/FeedbackDialog/LaunchButton.module.scss

Reverts carbon-design-system/gatsby-theme-carbon#977

Revert "fix(FeedbackDialog): update colors and animations"

---

packages/example/src/pages/test/spacing-audit.mdx
packages/gatsby-theme-carbon/src/components/MDXProvider/defaultComponents.js
packages/gatsby-theme-carbon/src/components/markdown/Abbr.js
packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss
packages/gatsby-theme-carbon/src/components/markdown/Sup.js
packages/gatsby-theme-carbon/src/templates/Homepage.js

Adds styling for sup and abbr tag

Add superscript

---

packages/gatsby-theme-carbon/src/components/ArticleCard/ArticleCard.js

Closes #
**New**
**Changed**
**Removed**

fix: down with tabs

---

packages/example/gatsby-config.js
packages/gatsby-theme-carbon/src/components/Footer/Footer.module.scss
packages/gatsby-theme-carbon/src/components/Header/Header.module.scss
packages/gatsby-theme-carbon/src/components/Switcher/Switcher.module.scss

Forgot the tokens for the switcher in dark mode. Doh!

style(switcher): fixed tokens for dark theme

---

packages/gatsby-theme-carbon/src/components/Switcher/Switcher.js

fix: added Racial Equity to switcher

---

packages/example/src/pages/contributions.mdx
packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss

style: removed the padding -closes #1074

---

packages/gatsby-theme-carbon/src/components/Switcher/Switcher.js

Closes #1115 
Adding IBM Workplace Design entry for the Switcher.

feat: adding workplace design into switcher

---

packages/gatsby-theme-carbon/src/components/Tabs/Tabs.js
packages/gatsby-theme-carbon/src/components/Tabs/Tabs.module.scss
yarn.lock

fix: remove light prop

---

packages/gatsby-theme-carbon/src/components/Layout.js
packages/gatsby-theme-carbon/src/components/Switcher/Switcher.js
packages/gatsby-theme-carbon/src/util/hooks/useId.js

fix: useLayoutEffect warnings

---

packages/gatsby-theme-carbon/src/components/FourOhFour/FourOhFour.module.scss
packages/gatsby-theme-carbon/src/components/Homepage/homepage.scss

Closes #1128 
Added link light styles for dark containers.

chore(404): makes links visible in dark container

---

packages/gatsby-theme-carbon/src/components/Switcher/Switcher.js

feat: update universal experiences to experience standards in switcher

---

packages/example/src/pages/components/Aside.mdx

fix: aside docs

---

packages/gatsby-theme-carbon/src/components/Switcher/Switcher.js

feat(switcher): add carbon for ibm products remove ix

---

.github/CODEOWNERS
packages/example/package.json
packages/example/src/pages/components/Aside.mdx
packages/example/src/pages/guides/v2-migration.mdx
packages/gatsby-theme-carbon/package.json
packages/gatsby-theme-carbon/src/components/ArticleCard/ArticleCard.js
packages/gatsby-theme-carbon/src/components/ArticleCard/article-card.scss
packages/gatsby-theme-carbon/src/components/Code/Code.module.scss
packages/gatsby-theme-carbon/src/components/FeatureCard/feature-card.scss
packages/gatsby-theme-carbon/src/components/FourOhFour/FourOhFour.module.scss
packages/gatsby-theme-carbon/src/components/Homepage/Banner.js
packages/gatsby-theme-carbon/src/components/Homepage/Callout.module.scss
packages/gatsby-theme-carbon/src/components/Homepage/homepage.scss
packages/gatsby-theme-carbon/src/components/MediumPosts/MediumPosts.module.scss
packages/gatsby-theme-carbon/src/components/Switcher/Switcher.js
packages/gatsby-theme-carbon/src/styles/internal/_page.scss
yarn.lock

updated Theme and Example to Gatsby 4.4 for the `next` branch. Once merged, I'll publish to npm under the `next` tag so we can test it against the Carbon site and IDL.
Also merged latest changes from `main`.

chore(theme): update to 4.4

---

packages/example/src/pages/guides/MDX.mdx

I didn't update the date though, as it was a minor change and didn't affect the content. Please let me know if I should do that.

Fixed a typo in "extremly"

---

.gitignore
README.md
package.json
packages/example/README.md
packages/example/src/gatsby-theme-carbon/components/Layout.js
packages/example/src/styles/Layout.module.scss
packages/example/src/styles/index.scss
yarn.lock

Closes #
No related issue
**New**
- Adding top banner for change to community model
**Changed**
- Added same community messaging to READMEs

chore(banner): add banner message for community contributions

---

.github/workflows/manual-release.yml
.github/workflows/release.yml
.gitignore
README.md
yarn.lock

Closes #1332
Setup continuous delivery from the main branch.

ci: add upto release workflow

---

yarn.lock

Closes #
**New**
**Changed**
**Removed**

chore: fix yarn lockfile

---

packages/example/src/gatsby-theme-carbon/components/Footer/index.js
yarn.lock

Closes https://github.com/carbon-design-system/carbon/issues/15636
**Changed**
- update footer links for compliance reasons

chore: add missing footer links for compliance

---

packages/example/gatsby-ssr.js
yarn.lock

Closes https://github.com/carbon-design-system/carbon/issues/15645
add common js

chore: add common js for compliance

---

packages/example/src/gatsby-theme-carbon/components/Layout.js
packages/gatsby-theme-carbon/src/components/Layout.js
packages/gatsby-theme-carbon/src/components/Switcher/index.js
packages/gatsby-theme-carbon/src/components/Tabs/Tabs.js
packages/gatsby-theme-carbon/src/util/context/NavContext.js

Fixed a few things as per the eslint rules.

fix(lint): imports, useMemo

---

packages/gatsby-theme-carbon/src/components/Switcher/Switcher.js
yarn.lock

Add Carbon for Cloud site in switcher.
FYI @sstrubberg
**New**
- add link to Carbon for Cloud

chore: add Carbon for Cloud in switcher

---

packages/example/src/pages/components/code-blocks.mdx
packages/gatsby-theme-carbon/src/components/Code/Code.js
yarn.lock

This PR aims at changing the hideCode prop to showAll prop as the naming makes more sense with showAll.

refactor: change hideCode prop to showAll prop

---

packages/gatsby-theme-carbon/gatsby-node.js
packages/gatsby-theme-carbon/gatsby-node.mjs
packages/gatsby-theme-carbon/package.json
yarn.lock

Closes #
**New**
**Changed**
**Removed**

fix: warnings

---

packages/gatsby-theme-carbon/src/components/Caption/Caption.module.scss

fix: caption styles

---

packages/gatsby-theme-carbon/README.md

Closes #
**New**
**Changed**
**Removed**

chore: readme

---

.github/workflows/release.yml

Also enhance release workflow to check for new commits and validate status before release,
so that we do not release if there are no new commits or if the validate workflow fails.
Closes #
**New**
**Changed**
**Removed**

feat(release): batch release of all packages weekly

---

README.md
yarn.lock

Closes #
**New**
**Changed**
**Removed**

chore: deploy

---

packages/example/gatsby-config.js

Closes #
**New**
**Changed**
**Removed**

chore: remove pathprefix

---

.github/workflows/gh-pages.yml

Closes #
**New**
**Changed**
**Removed**

chore: copy images deployment

---

.github/workflows/gh-pages.yml

Closes #
**New**
**Changed**
**Removed**

chore: undo copy

---

.github/workflows/gh-pages.yml

Closes #
**New**
**Changed**
**Removed**

chore: build:clean for deployment
