packages/gatsby-theme-carbon/gatsby-config.js

This prevents remark-image from shrinking photos that are blurry. This behavior is not ideal with lots of cards that need to be sized the same.

fix: remove size-by-density remark image feature

---

packages/gatsby-theme-carbon/gatsby-config.js
packages/gatsby-theme-carbon/package.json
yarn.lock

Copies files from markdown pages folders (for example: gif or svg images) to the public folder so they can be easily used on a page. 
https://www.gatsbyjs.org/packages/gatsby-remark-copy-linked-files

chore: add gatsby-remark-copy-linked-files

---

packages/gatsby-theme-carbon/src/components/Main.js
packages/gatsby-theme-carbon/src/components/NextPrevious/NextPrevious.js

chore: This allows for pages to be generated without existing in the nav config. These floating pages should be avoided for UX and SEO discoverability, but we don't want to break the build of something is left out or intentionally excluded

fix: don't render next/prev for floating pages

---

packages/example/src/pages/components/DoDontExample.mdx
packages/gatsby-theme-carbon/src/components/AnchorLinks/anchor-links.scss
packages/gatsby-theme-carbon/src/components/Code/Code.js
packages/gatsby-theme-carbon/src/components/Code/_code.scss
packages/gatsby-theme-carbon/src/components/ResourceCard/resource-card.scss
packages/gatsby-theme-carbon/src/styles/index.scss

ref #43
closes #40
- fix do-don't example error
- updates code snippet styles, was missing font and default text color so looked broken on dark background in the footer. 
- fix ResourceCard style bugs
Not fixed
```
Warning: Failed prop type: Invalid prop `children` of type `object` supplied to `CodeSnippet`, expected `string`.
```

fix: console errors, code styles & card bug

---

packages/gatsby-theme-carbon/gatsby-config.js
packages/gatsby-theme-carbon/package.json
packages/gatsby-theme-carbon/src/components/Homepage/homepage.scss
packages/gatsby-theme-carbon/src/styles/index.scss
yarn.lock

Closes #48 
In this PR we switch to pre-fetching the google fonts to improve font-loading performance and also to offer weights other than those provided by the `@carbon/type` package.
To that end, this PR also also allows devs to configure additionalFontWeights other than the defaults as a theme option:
```js
// gatsby-config.js
__experimentalThemes: [
{
resolve: 'gatsby-theme-carbon',
options: {
// will get added to default [300, 400, 600]
additionalFontWeights: [200]
},
},
],
```

feat: switch font-loading to prefetch. Add font weight option

---

packages/gatsby-theme-carbon/src/components/FeatureCard/feature-card.scss
packages/gatsby-theme-carbon/src/components/ResourceCard/resource-card.scss

Fix for mis-alignment at mobile breakpoint. Also moves styles into correct sass file 🤦‍♀

fix(featureCard): update mobile breakpoint styles

---

packages/gatsby-theme-carbon/src/components/DoDontExample/do-dont-example.scss
packages/gatsby-theme-carbon/src/styles/_page.scss

couple small styling issues I noticed working on IDL site
- need the max width for images for larger gif and svg images
- had the bottom padding wrong for do-dont

fix: max-width for images and dodont spacing

---

packages/example/src/pages/components/FeatureCard.mdx
packages/gatsby-theme-carbon/gatsby-config.js
packages/gatsby-theme-carbon/src/components/FeatureCard/FeatureCard.js
packages/gatsby-theme-carbon/src/components/FeatureCard/feature-card.scss

* pixel sliver for some images, 
* image distortion on mobile
* over-aggressive image compression
* add webp support for browsers that allow it (chrome, firefox, edge)
This changes the image's default `object-fit` to cover rather than stretch/distort.
In the future, `object-position` can be added to allow for controlling the piece of the visible image (top/bottom/left/right/center). In the mean time, devs can control this property with their own styling solutions.

Feature card update

---

packages/example/gatsby-config.js

Removes the old way of passing manifest options as theme options. We'd rather folks just pass it directly instead of currying it.

chore: remove unused config

---

packages/example/gatsby-config.js
packages/gatsby-theme-carbon/gatsby-config.js
packages/gatsby-theme-carbon/src/components/Meta.js
packages/gatsby-theme-carbon/src/util/hooks/useMetadata.js

This will automatically inject a title, description and keywords into the head of your document. Simply provide them to siteMetadata in your `gatsby-config.js` file.
```js
module.exports = {
siteMetadata: {
title: 'Gatsby Theme Carbon',
description: 'A Gatsby theme for the carbon design system',
keywords: 'gatsby,theme,carbon',
},
__experimentalThemes: [
{
resolve: 'gatsby-theme-carbon',
},
],
};
```

feat: automatically supply meta-data to head

---

README.md
packages/example/gatsby-config.js
packages/gatsby-theme-carbon/gatsby-config.js
packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.module.scss
packages/gatsby-theme-carbon/src/components/ResourceCard/resource-card.scss

Devs need to specify italic variants if they're needed. Documentation
added. closes #135, closes #134

fix: italic plex and scrolling page tabs

---

packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.module.scss

Resolves #145
Prevents horizontal scrollbar (or the "space" for the scrollbar) always showing even when the page tabs aren't overflowing their container.

fix(page-tabs): set overflow-x to auto

---

README.md
packages/gatsby-theme-carbon/gatsby-config.js
packages/gatsby-theme-carbon/src/components/Switcher/Switcher.js

WebP is now disabled by default but can be enabled by turning on the config.

chore: add ai to the switcher link

---

packages/example/src/pages/components/DoDontExample.mdx
packages/gatsby-theme-carbon/src/components/Aside/aside.scss
packages/gatsby-theme-carbon/src/components/Header/Header.js
packages/gatsby-theme-carbon/src/components/Header/Header.module.scss
packages/gatsby-theme-carbon/src/components/markdown/markdown.scss

- Fix alignment for aside closes https://github.com/carbon-design-system/gatsby-theme-carbon/issues/151
- Update do-dont demo to be correct size closes https://github.com/carbon-design-system/gatsby-theme-carbon/issues/141
- Fixes alignment of switcher/close icons closes #142
- Fixes paragraph alignment/spacing on grid closes https://github.com/carbon-design-system/gatsby-theme-carbon/issues/99

fix: various small fixes (Aside, DoDont & switcher icons)

---

packages/gatsby-theme-carbon/src/components/DoDontExample/do-dont-example.scss

Makes sure images span full width of DoDont example card. (noticed when using a svg inside the example that was smaller)

fix(DoDont): fix for images that aren't square or are smaller

---

packages/example/src/pages/components/Aside.mdx
packages/example/src/pages/components/markdown.mdx
packages/gatsby-theme-carbon/src/components/Header/Header.module.scss
packages/gatsby-theme-carbon/src/components/PageDescription/PageDescription.module.scss
packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss

closes #182, closes #172
Also adds styles for blockquote `cite` tag and uses realistic block quote examples with citations to the docs

fix: update various markdown widths

---

packages/example/src/pages/components/AnchorLinks.mdx
packages/example/src/pages/components/markdown.mdx
packages/gatsby-theme-carbon/gatsby-config.js
packages/gatsby-theme-carbon/package.json
packages/gatsby-theme-carbon/src/components/AnchorLinks/AnchorLink.js
packages/gatsby-theme-carbon/src/components/AutolinkHeader/AutolinkHeader.js
yarn.lock

`remark-slug` handles resetting the slugger per page generation

fix: use remark to generate slugs per page

---

packages/example/src/gatsby-theme-carbon/components/LeftNav/ResourceLinks.js
packages/gatsby-theme-carbon/src/components/LeftNav/LeftNav.module.scss
packages/gatsby-theme-carbon/src/components/LeftNav/ResourceLinks.js

Also adds `ResourceLinks` prop `shouldOpenNewTabs` to open outgoing resource links in a new tab to bring in functionality from #79.

fix: update lefnav icon logic

---

packages/gatsby-theme-carbon/src/components/Caption/caption.scss

closes #190 
Brings caption styles in line with dl/carbon.
Captions should match paragraphs at sm/md breakpoints, but max out at 6/12 columns for lg breakpoint.

fix: update caption widths

---

lerna.json
packages/example/package.json
packages/gatsby-theme-carbon/package.json
packages/gatsby-theme-carbon/src/components/LeftNav/LeftNav.module.scss
packages/gatsby-theme-carbon/src/components/LeftNav/LeftNavItem.js
packages/gatsby-theme-carbon/src/components/LeftNav/ResourceLinks.js

This fixes a prop-type error from 1.3.1 and also address a side-nav one that's been hanging out for a while.

Prop type fix

---

packages/example/src/pages/components/ArticleCard.mdx

closes #214 
ArticleCard docs incorrectly lists aspectRatio as a prop, this removes it from the docs

fix: remove incorrect prop from ArticleCard docs

---

packages/gatsby-theme-carbon/src/components/AnchorLinks/AnchorLinks.module.scss

Let's do this again! 😂 
*Changed* 
- Updates `margin-bottom: $spacing-02;` -> `margin-bottom: $spacing-03;`  changing the sapce under AnchorLinks from 4px to 8px, to match the IDL site.
Before: 
Now: 
Matching this spacing:

chore: update space between anchorlinks

---

packages/example/src/pages/components/Accordion.mdx
packages/gatsby-theme-carbon/src/components/Accordion/Accordion.js
packages/gatsby-theme-carbon/src/components/Accordion/Accordion.module.scss

Closes #251 
- Updated example to add paragraphs and lists as children
- Added our grid component instead of trying to fake it with % which ends up slightly off-grid
- Updated font size styles for website specific rules based on Mike's comments in the issue
FYI @sstrubberg

fix: accordion styles

---

packages/example/src/pages/components/Accordion.mdx
packages/example/src/pages/components/AnchorLinks.mdx
packages/example/src/pages/components/ArticleCard.mdx
packages/example/src/pages/components/Aside.mdx
packages/example/src/pages/components/Caption.mdx
packages/example/src/pages/components/DoDontExample.mdx
packages/example/src/pages/components/FeatureCard.mdx
packages/example/src/pages/components/Grid.mdx
packages/example/src/pages/components/ImageCard.mdx
packages/example/src/pages/components/PageDescription.mdx
packages/example/src/pages/components/ResourceCard.mdx
packages/example/src/pages/components/Tabs.mdx
packages/example/src/pages/components/Video.mdx
packages/example/src/pages/components/markdown.mdx

Closes #260 
Edited the code snippets by adding the src for the link and a path for where to go to shadow the component. 
I think I got them all but it might be good to check that I didn't miss any code blocks! 
So neat and pretty now! 🎉

260 Updates component codeblock examples with new features 

---

packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.module.scss

closes #223
Updates mobile tab spacing to be 16px on the right

fix: update page tabs spacing at mobile

---

packages/example/gatsby-config.js
packages/example/src/pages/guides/configuration.mdx

This updates the documentation to use the official plugin approach

docs: remove experimental refs

---

packages/gatsby-theme-carbon/src/components/Tabs/Tabs.module.scss

Hi,
I looked around in the example tabs page (https://gatsby-theme-carbon.now.sh/components/Tabs/) and noticed that when the mouse is pressed (:active), the tab label acts weird IMO.
IMO this janky behavior is a bug, and by looking at the carbon design system's storybook(http://react.carbondesignsystem.com/?path=/story/tabs--default) it seems that it is not intended.
If you think this is the intended behavior, feel free to ignore and close this PR :) 
great job on the theme!! it looks and feels awesome!

fix: remove janky :active class from tabs component

---

packages/gatsby-theme-carbon/gatsby-config.js

Allows restricting MDX extensions to only `.mdx`

fix: closes #284

---

packages/gatsby-theme-carbon/src/components/Accordion/Accordion.js
packages/gatsby-theme-carbon/src/components/Code/Code.module.scss
packages/gatsby-theme-carbon/src/components/NextPrevious/NextPrevious.module.scss

closes #286 
closes #287
- removes gutter for accordion
- adjusts code snippet to align with 8 col row components
- uses `carbon--gray-90` for next-prev. There is no theme token to represent this value with the white theme.

Next prev accordion

---

packages/gatsby-theme-carbon/src/components/Container/Container.js
packages/gatsby-theme-carbon/src/components/Homepage/Callout.module.scss
packages/gatsby-theme-carbon/src/components/Homepage/homepage.scss
packages/gatsby-theme-carbon/src/components/ResourceCard/resource-card-group.scss

Noticed a couple of issues while working on the Carbon homepage. Fixes border for card groups on the homepage. and adds the container class to the homepage (we're using this for some styling)
makes link styling specifc to the callout component, otherwise it was affecting cards and anything else on the page

fix: homepage style bugs

---

packages/gatsby-theme-carbon/src/components/DoDontExample/do-dont-example.scss

Fixes extra space appearing below images inside the do-dont example. 
related to https://github.com/carbon-design-system/design-language-website/pull/119

fix: extra space below images in dodont

---

packages/gatsby-theme-carbon/src/styles/internal/_page.scss

closes #298
I'd like to deal with the page styles in a more holistic way. I think we could start planning for refactoring them along with the markdown styles.

fix: don't restrict grid width on the homepage

---

packages/example/src/pages/components/markdown.mdx
packages/example/src/pages/guides/configuration.mdx
packages/example/src/pages/index.mdx
packages/gatsby-theme-carbon/gatsby-node.js
packages/gatsby-theme-carbon/src/components/Layout.js
packages/gatsby-theme-carbon/src/components/Meta.js
packages/gatsby-theme-carbon/src/templates/Default.js
packages/gatsby-theme-carbon/src/templates/Homepage.js
yarn.lock

this PR passes the MDX frontmatter title into the `<Meta>` component HTML title element. not sure how configurable we want this to be, but this is an option for getting dynamic page titles in the format we're looking for in the IDL site

feat: pass MDX frontmatter title into page `<title>`

---

packages/example/gatsby-config.js
packages/gatsby-theme-carbon/src/components/LeftNav/LeftNavItem.js

Took a shot at a fix to resolve #265 
Slightly modifies the left nav item to more explicitly check the paths against one another, rather than relying on `includes()`.

fix(navigation): explicitly match paths to links for selected state

---

packages/example/src/pages/components/markdown.mdx
packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss

Source
- Add a css selector for .list-style
- I had to reorder the blockquote css below list-item's due to stylelint's `no-descending-specificity`
Example
- Fix the anchor link, it wasn't working
- Expand the block quote example
Closes #261

fix(blockquote): list text color

---

packages/gatsby-theme-carbon/src/components/DoDontExample/do-dont-example.scss

Closes #317 
Changed the class being selected from the video styles in `do-dont-example.scss`
**Testing**
Check and see that the video play button is in the center in a DoDontExample

fix(DoDontExample): changed targeted class so video button is not off center

---

packages/gatsby-theme-carbon/package.json
packages/gatsby-theme-carbon/src/components/BackToTopBtn/BackToTopBtn.js
packages/gatsby-theme-carbon/src/components/BackToTopBtn/BackToTopBtn.module.scss
packages/gatsby-theme-carbon/src/components/BackToTopBtn/index.js
packages/gatsby-theme-carbon/src/components/Header/Header.module.scss
packages/gatsby-theme-carbon/src/styles/internal/_global.scss
packages/gatsby-theme-carbon/src/styles/internal/_page.scss
packages/gatsby-theme-carbon/src/styles/internal/_website-side-nav.scss
packages/gatsby-theme-carbon/src/templates/Default.js
packages/gatsby-theme-carbon/src/templates/Homepage.js
yarn.lock

Brings in BackToTopBtn component, grid additions and shell overrides to this repo. This removes our dependency on the deprecated @carbon/addons-website package. 
- Make sure UI Shell looks correct (side nav/header)
- Make sure back to top button looks correct
- Make sure grid component gutter classes are being applied correctly

refactor: remove addons-website dependency

---

packages/example/src/pages/components/ResourceCard.mdx

Removed stray backtick in `ResourceCard` code block

fix(docs): remove stray backtick

---

packages/gatsby-theme-carbon/src/components/AnchorLinks/AnchorLinks.module.scss
packages/gatsby-theme-carbon/src/components/ArticleCard/article-card.scss
packages/gatsby-theme-carbon/src/components/Caption/caption.scss

- type size broke on article cards w/ latest Carbon - fixed
- updates spacing for captions below video
- token color change broke anchor link color - fixed  ref #369

fix: article card type style and caption spacing

---

packages/gatsby-theme-carbon/src/components/Video/Video.js

#383 but for the poster images
Asset's are 404ing because we look for them at the root directory (ibm.com) instead of the prefixed path (ibm.com/design/language).

fix: add path prefix to poster

---

packages/gatsby-theme-carbon/src/components/Switcher/Switcher.module.scss

closes #388 
Note: rather than the type component I used the shadows from the shell menu dropdowns: http://react.carbondesignsystem.com/?path=/story/ui-shell--header-base-w-navigation

fix: Add switcher drop shadow closes #388

---

packages/example/src/pages/guides/configuration.mdx
packages/gatsby-theme-carbon/src/components/Meta.js

closes #403 
Adds option to prepend the title before the site name 
`prepend`: "Configuration - Gatsby Theme Carbon"

feat: add prepend option to titleType

---

packages/example/src/pages/guides/navigation/sidebar.mdx
packages/example/src/pages/guides/navigation/tabs.mdx
packages/gatsby-theme-carbon/src/components/GlobalSearch/GlobalSearch.module.scss
packages/gatsby-theme-carbon/src/components/GlobalSearch/Menu.js

Pages with tabs could share the same title. If this is the case, we can add the last bit of path as an identifier to set them apart.
`→` character got okayed by @designertyler 
**You can search for “Navigation” to see it working**

[Search] add tab to distinguish pages with the same title

---

packages/gatsby-theme-carbon/config/lunr-options.js

closes #413 
This removes the [Lunr stemmer](https://www.gatsbyjs.org/packages/gatsby-plugin-lunr/#using-plugins) which is goofing up our search index and search results.
**Testing:** search for "Navigation" or any other full page title at https://gatsby-theme-carbon.now.sh and compare to this deploy preview. 
We should now show results throughout the user typing interaction rather than randomly empty results in the middle and end.

[Search]: fix poor search results

---

packages/gatsby-theme-carbon/src/components/GlobalSearch/GlobalSearch.js

If escape is used to clear, we don't properly set manage focus state even though we direct focus to the input. This results in us failing to focus the search button correctly on close.

fix: manage focus with escape clear

---

packages/example/src/data/nav-items.yaml
packages/example/src/pages/components/MDX.mdx
packages/example/src/pages/components/markdown.mdx
packages/gatsby-theme-carbon/src/components/PageHeader/PageHeader.js
packages/gatsby-theme-carbon/src/templates/Default.js

closes #409 
I think this stands to be a particularly powerful pattern for things like theming individual pages if we identify future components where we _want_ to permit that sort of deviation.

feat: export custom Title component from MDX

---

packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss

Closes #424 
**Changed**
- adds `16px` right padding for paragraph at mobile breakpoints

fix(paragraph): add right padding for mobile sizes

---

packages/gatsby-theme-carbon/gatsby-ssr.js

This allows us to easily check which version of gtc a site is using.

chore: add gtc version meta tag

---

packages/example/src/pages/components/ArticleCard.mdx
packages/gatsby-theme-carbon/src/components/ArticleCard/article-card.scss

Adds in completely missing styles for subtitle on dark/dark-disabled

fix(ArticleCard): add missing styles for subtitle on dark cards

---

packages/gatsby-theme-carbon/index.js

This exports `InlineNotification` from the main module.
Now this works:
```js
import {InlineNotification} from 'gatsby-theme-carbon';
```

fix: export InlineNotification

---

yarn.lock

Should fix issues with `404`s in clients with a site open when an update is published.

chore: update gatsby deps

---

packages/example/gatsby-config.js
packages/example/src/pages/guides/configuration.mdx
packages/gatsby-theme-carbon/gatsby-config.js
packages/gatsby-theme-carbon/src/components/EditLink/EditLink.js

fixes carbon-design-system/gatsby-theme-carbon#455
Closes #455 
Adds a configuration option to specify what branch the `EditLink` should point to when opening github.
**New**
- N/A
**Changed**
- config options for repository not accepts branch
**Removed**
- N/A

fix(EditLink): Adds branch option to edit url

---

packages/gatsby-theme-carbon/src/components/Accordion/Accordion.module.scss

Added 4rem of padding-right to accordion per [Mike's request](https://github.com/IBM-Design/idr/issues/133)

fix: accordion padding

---

packages/gatsby-theme-carbon/src/components/ImageGallery/ImageGalleryImage.js
packages/gatsby-theme-carbon/src/components/ImageGallery/ImageGalleryImage.module.scss

closes #492 
Image galleries lacked margin after the spacing re-write

fix: image gallery spacing

---

packages/gatsby-theme-carbon/src/components/InlineNotification/InlineNotification.module.scss

Favors universal spacing introduced by #373 
closes #453

fix: remove extra margin on inline notification

---

packages/gatsby-theme-carbon/src/components/ImageCard/ImageCard.js

Closes #514 
Currently unless you add the `disabled` prop, an `ImageCard` will always render as an anchor.
This is problematic if you don't also provide an `href` (which is not a required prop, either).
Recently on the IBM Security design team, we've come across a situation where we want the positioning and styling of an `ImageCard` within a grid, but we don't need to link it anywhere. (So, we aren't providing an `href`). The `ImageGalleryCard` would not apply well for our designs/situation., and we also don't want to apply `disabled={true}` to `ImageCard` which would apply "do not click" cursor + icon + give an impression that the Card would be clickable under other circumstances. So we wanted to propose a fix here.
Please let me know what you think -- thanks!
**Changed**
- only apply …

fix(image-card): render as div if no href is provided

---

packages/gatsby-theme-carbon/src/components/Switcher/Switcher.js

- Adds workplace link
- Will enable events link if the current date is greater than or equal to Dec 2 2019

chore: update switcher links closes #537 closes #539

---

packages/gatsby-theme-carbon/src/components/Container/Container.js

Closes #563 
Currently the main content of every page is wrapped in a `div`, not an HTML5 sectioning element.
This generates DAP errors for [checkpoint 2.4.1](http://www.ibm.com/able/guidelines/ci162/bypass_blocks.html)
By wrapping the page in a `main` sectioning element, assistive tech will be able to recognize the main content of the page. This will likewise remove many DAP errors being generated per page, per orphaned element (for example, removes approximately 9 errors on the demo site homepage).
**Changed**
- update `Container` component to wrap page content in `main` HTML5 sectioning element

fix(container): wrap page content in main HTML5 sectioning element

---

packages/gatsby-theme-carbon/src/components/Code/PathRow.js
packages/gatsby-theme-carbon/src/components/Code/Sidebar.js

Closes #572 
Adds `alt` attribute to svg elements inside anchors used in the `CodeBlock` component (see #572 for context)
**Changed**
- add `alt` attribute to svgs

fix(code-blocks): add alt value to svg inside anchors

---

packages/gatsby-theme-carbon/src/components/Header/Header.module.scss

Closes #570 
**Changed**
- make the `SkipToContent` link text white so that it makes AA minimum contrast requirements

fix(skip-to-content): make link text white to meet AA contrast

---

packages/example/gatsby-config.js
packages/example/src/pages/guides/configuration.mdx
packages/gatsby-theme-carbon/gatsby-config.js
packages/gatsby-theme-carbon/src/components/Meta.js
packages/gatsby-theme-carbon/src/util/hooks/useMetadata.js

Closes #557
Adds default language via `lang` attribute to `HTML` element, per [Checkpoint 3.1.1.](https://www.ibm.com/able/guidelines/ci162/language_of_page.html)
**New**
- add `lang` to `siteMetadata`

feat(html): add default lang to site metadata, pass to helmet

---

packages/example/src/pages/guides/navigation/sidebar.mdx
packages/gatsby-theme-carbon/src/components/LeftNav/LeftNav.js
packages/gatsby-theme-carbon/src/components/LeftNav/LeftNavItemProvider.js

Refactor the Graphql query of `src/data/nav-items.yaml` to a separate file - `LeftNavItemProvider.js`.  This enables augmentation or replacement of the nav item list via Gatsby Theme shadowing.
For example, adding the following to the project will append a new nav item to the nav items gatsby-theme-carbon parsed from `/src/data/nav-items.yaml`:
```javascript
// src/gatsby-theme-carbon/components/LeftNav/LeftNavItemProvider.js
import {useNavItems as themeUseNavItems} from 'gatsby-theme-carbon/src/components/LeftNav/LeftNavItemProvider';
export function useNavItems() {
const navItems = themeUseNavItems();
return navItems.concat({
title: 'Shadow Nav Item!',
description: 'This is a nav item added via shadowing',
pages: [
{path: '/page1', title: 'Test Page 1'},
{path: '/page2', title: 'Test …
```

feat(nav): Enable override of nav item list via shadowing

---

packages/gatsby-theme-carbon/src/components/Switcher/Switcher.module.scss

Closes #579
Increases max-height of switcher so that bottom link isn't cut off.
- make sure all links are visible in switcher on desktop
- @jeanservaas make sure spacing below bottom link is correct, not 100% sure what it should be

fix: increase max-height of switcher

---

packages/gatsby-theme-carbon/src/components/Container/Container.js
packages/gatsby-theme-carbon/src/styles/internal/_page.scss

closes #578 
Fix for Carbon homepage, no-gutter classes aren't being applied because the homepage doesn't use the .container class. This should also fix the max breakpoint feature card mis-alignment
Added the container class back to the homepage template
Ensure that this won't break anything - check components using the grid, and the aside component which has nested grid classnames.

fix: remove container classname scope

---

packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss

Closes #582
Closes #503 
Closes #470 
**Changed**
- Updated paragraph and list spacing, 16px to the right at mobile, 32px at tablet and above

fix: update right spacing for paragraphs and lists

---

packages/gatsby-theme-carbon/src/components/ImageCard/ImageCard.js

Currently we cannot pass a `style` attribute to the `ImageCard` component because it doesn't allow additional props. This PR proposes adding `...rest` to allow that 👍 
**New**
- add spread operator to pass through additional props

fix(image-card): allow additional props

---

packages/gatsby-theme-carbon/src/components/AutolinkHeader/AutolinkHeader.module.scss

Closes #601 
Let me know if you want any additional `:focus` state styles. At a minimum to fix #601, I just fixed the `opacity` issue. 👍 
**Changed**
- set `opacity: 1` when header link has `:focus` state

fix(autolink-headers): set opacity to 1 when links are focussed

---

packages/example/src/pages/components/AnchorLinks.mdx
packages/gatsby-theme-carbon/src/components/AnchorLinks/AnchorLinks.module.scss

closes #586
Anchor link width now matches up to 8 columns width (4 columns each when split into two)
Updated the example to have more items to show the 2 column layout

fix: put anchor link columns on grid 

---

packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss

Switches to text-indent for hanging quotes. Adds 16px margin left on mobile.
closes #630

fix: add mobile block quote indent and hanging quote closes #615

---

packages/gatsby-theme-carbon/src/components/GlobalSearch/Menu.js
packages/gatsby-theme-carbon/src/components/Tabs/Tabs.js

Closes #649 
Gatsby recently turned on `eslint-plugiun-jsx-a11y` for Gatsby projects (https://github.com/gatsbyjs/gatsby/pull/19946) this means that the issues will show up in the dev console. This is awesome but some of their config is overzealous.
In particular, it fails to include the recommended exceptions to the [no-noninteractive-element-to-interactive-role](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-noninteractive-element-to-interactive-role.md#rule-details).
The two failures we see in the error message would be ignored with this rule. Both of the w3 examples used to build this component would fail this check: 
1. [Menu](https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html)
2. …

fix: ignore rule exceptions

---

packages/example/src/pages/index.mdx
packages/gatsby-theme-carbon/src/components/Homepage/homepage.scss

Resolves https://github.com/carbon-design-system/carbon-website/issues/792
Resolves https://github.com/carbon-design-system/carbon-website/issues/536
The links on the dark container of the homepage are not styled for `:hover`, `:active`, `:active:visited`, or `:active:visited:hover` states. As a result, these states show default `bx--link` colors which are not accessible against the dark background. (The also applied to the focus outline).
**New**
- add example link outside of homepage callout so that the modified link styles can be easily tested.
**Changed**
- add style overrides for links on the dark container background of the homepage.

fix(homepage): use blue40 for links on dark homepage container

---

packages/example/src/pages/components/FeatureCard.mdx

Closes #667 
remove sub title in the second feature card

remove sub-title in feature card demo

---

packages/gatsby-theme-carbon/src/components/InlineNotification/InlineNotification.js
packages/gatsby-theme-carbon/src/components/InlineNotification/InlineNotification.module.scss

Closes #718
Removes double border, updates width at tablet breakpoint to be 6 cols to match text width.
Test that `InlineNotification` styles look correct at all breakpoints

fix(inlineNotification): remove extra border and update width at tablet breakpoint

---

packages/gatsby-theme-carbon/src/components/DoDontExample/do-dont-example.scss
packages/gatsby-theme-carbon/src/components/DoDontRow/DoDontRow.module.scss

fix: remove extra space beneath do-dont-captions

---

packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss

Closes #720 
Added 1ch to margin-left for OLs but not nested OLs.

fix(Markdown):OLs margin-left

---

packages/gatsby-theme-carbon/src/components/FeedbackDialog/Form.module.scss

When having a viewport width equal or a little lower than 671. The feedback form has a probably unintended space on the right of the bottom form button row. 
This is resulting from the max-width definition of bx--btn.
IMO a proper change would be to override the max-width with 50%.
**Changed**
- Fixed unintended space in feedback dialog button row.

Fix trailing space within feedback dialog button row.

---

packages/gatsby-theme-carbon/src/components/Switcher/index.js

`components/Switcher/index.js` omits to export `SwitcherDivider` and `SwitcherLink`, which are needed if you want to shadow `Switcher`.

Export SwitcherDivider and SwitcherLink from Switcher

---

packages/example/src/pages/guides/configuration.mdx
packages/gatsby-theme-carbon/gatsby-config.js

Add a [`remarkPlugins`](https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/#remark-plugins) option to pass along to `gatsby-plugin-mdx`.
The reason this is required in addition to the `gatsbyRemarkPlugins` option is because `gatsbyRemarkPlugins` has had numerous issues with getting plugins to work with it:
- https://github.com/gatsbyjs/gatsby/issues/21866
- https://github.com/gatsbyjs/gatsby/issues/16983
- https://github.com/gatsbyjs/gatsby/issues/8009
- https://github.com/gatsbyjs/gatsby/issues/9103
- https://github.com/gatsbyjs/gatsby/issues/6648
But the `remarkPlugins` option works great and is usually the workaround that is eventually used. So exposing this option to the user helps.
**New**
- added a `remarkPlugins` theme option to be passed to `gatsby-plugin-mdx`
- added an example …

feat: add remarkPlugins theme option

---

packages/gatsby-theme-carbon/src/components/NextPrevious/NextPrevious.js

Closes #822 
Fixes the case where path prefix contains a segment which is also a tab title.

fix: nextprev logic with pathPrefix

---

packages/gatsby-theme-carbon/src/components/Tabs/Tabs.module.scss

This is a problem downstream, our listbox overrides here impacted `Dropown`s on other pages (like IDL's icon filter row)

fix: remove listbox overrides

---

packages/example/src/pages/components/Title.mdx

H4s and tables directly next to each other are too close visually. I think table should be mentioned here as another component which should use <Title> instead of H4 above it.
**Changed**
- added "table" to the copy

chore: add table to components using <Title> tag

---

packages/example/src/pages/components/FeatureCard.mdx
packages/gatsby-theme-carbon/src/components/ResourceCard/resource-card.scss

Closes #883 
Targeted the SVG in the ResourceCard and gave it icon-01. Update the FeatureCard docs to have one feature card using the default color and one feature card using dark mode.

fix(ResourceCard-FeatureCard): icon was the wrong color

---

packages/example/src/pages/guides/navigation/sidebar.mdx

Closes #908
fix: Remove ".js" extension from the import in the sample code for overriding the NavItems component to avoid an infinite loop during loading, resolves #908
**New**
- none
**Changed**
- Changed sample code for NavItems component.
**Removed**
- none

fix: Remove ".js" extension from the import in the sample code for overriding the NavItems component to avoid an infinite loop during loading

---

packages/gatsby-theme-carbon/src/components/GlobalSearch/GlobalSearch.js

Updates GlobalSearch to conditionally set `aria-activedescendent`. Before with no results available `aria-activedescendent` was set incorrectly to 0 even with the listbox closed which was causing an error in the Accessibility Checker because the ID referenced had no corresponding list item. 
Now it's only set to a list item id when results are present :surfer: 
1) Go to the theme demo
2) Confirm that `aria-activedescendent` isn't present on the GlobalSearch's `<input>`
3) Type any letter to get some search results and reveal the listbox
4) Confirm that `aria-activedescdendent` is set to 0 on the GlobalSearch's `<input>`
5) Confirm no errors in Accessibility Checker pertaining to `aria-activedescendent`

fix(GlobalSearch): add conditional set to aria-activedescendent

---

packages/gatsby-theme-carbon/gatsby-node.js

The block of code doesn't work in conjunction with some customization (e.g. when `page.component` is defined to point to a template or when pages are not in `src/pages`. Adding a blog to avoid re-running the block of code if the MdxNode has been already defined will permit to create additional `onCreatePage` method to apply custom logic.
**Changed**
- gatsby-node.js

Permit overwrite of MdxNode field addition to page context

---

packages/gatsby-theme-carbon/src/components/Switcher/Switcher.js

Closes #
Refs #984 
**Removed**
- Removed `IBM Web Standards` url from the switcher

chore(switcher): removing web standards url per request

---

packages/gatsby-theme-carbon/src/components/BackToTopBtn/BackToTopBtn.module.scss
packages/gatsby-theme-carbon/src/components/FeedbackDialog/FeedbackDialog.js
packages/gatsby-theme-carbon/src/components/FeedbackDialog/LaunchButton.js
packages/gatsby-theme-carbon/src/components/FeedbackDialog/LaunchButton.module.scss
packages/gatsby-theme-carbon/src/templates/Homepage.js

Closes #886 
**Changed**
- closed state launch btn now matches `BackToTop` btn color
- expanded state background color now matches closed state hover color
- added a white box-shadow to `BackToTop` btn focus state to match feedback launch btn focus state
**Removed**
- filled face icon for launch btn

fix: feedback button colors

---

packages/gatsby-theme-carbon/src/components/Switcher/Switcher.js

Closes #847
- updating aria label so it won't be redundant for screen reader

fix: switcher aria label text

---

packages/example/src/pages/guides/navigation/tabs.mdx

Following the existing guidance on tabs with apostrophes with `gatsby@2.24.67` results in an error:
```
ERROR #11321  PLUGIN
"gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:
missed comma between flow collection entries at line 7, column 11:
'What's new',
^/Users/taylorjones/dev/ibm/design/src/pages/team/content-design/knowledge-center/whats-new.mdx: missed comma between flow collection entries at line 7, column 11:
'What's new',
^
31 |   const createAndProcessNode = path => {
32 |     const fileNodePromise = createFileNode(path, createNodeId, pluginOptions).then(fileNode => {
> 33 |       createNode(fileNode);
|       ^
34 |       return null;
35 |     });
36 |     return fileNodePromise;
File: node_modules/gatsby-source-filesystem/gatsby-node.js:33:7 …
```

fix(navigation): use proper apostrophe/quote syntax

---

packages/gatsby-theme-carbon/package.json
yarn.lock

Bumped up the version number so that it includes the fix needed for https://github.com/carbon-design-system/carbon-website/pull/1860
This allows a user to pass `![GATSBY_EMPTY_ALT](./image.png)` to achieve `alt=""`. This is needed in some scenarios, such as when a link is wrapping subtext and an image. The text would be repeated if the alt text is provided. 
https://www.gatsbyjs.com/plugins/gatsby-remark-images/?=gatsby-remark#usage-in-markdown

chore(package): update package to include upstream bug fix

---

packages/example/src/pages/guides/npm-scripts.mdx
packages/gatsby-theme-carbon/src/components/Footer/Footer.module.scss

The word _Sites_ at the beginning should be plural, and not _Site's_.

docs: fix typo in npm-scripts.mdx

---

packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js
packages/gatsby-theme-carbon/src/templates/Default.js

Closes issue found on carbon website - from theme: 
- https://github.com/carbon-design-system/carbon-website/issues/1554
-  https://github.com/carbon-design-system/carbon-website/issues/1716
**Changed**
Added. unique aria labels for tabs

fix(page-tabs): nav aria unique labels

---

packages/gatsby-theme-carbon/gatsby-config.js
packages/gatsby-theme-carbon/src/components/FourOhFour/FourOhFour.module.scss

Closes #1042 
Closes #1069 
- updates gatsby-config to point to main branch instead of master 
- changes color token for anchor links in 404 page (tested with diff themes)

fix: 404 link color and config branch as main

---

packages/gatsby-theme-carbon/src/components/Header/Header.module.scss

Closes #1086 
I was able to use some leftover header code to add/remove style with the search is clicked.
To test make sure you can open and use search on all screen sizes. Also make sure the header, titled "Gatsby Theme Carbon" can be clicked on and returns you to the root of the site.

style: fixes z-index when search is open

---

packages/example/gatsby-config.js
packages/gatsby-theme-carbon/src/components/Header/Header.js
packages/gatsby-theme-carbon/src/components/Header/Header.module.scss

More z-index issues with the header. Theres probably a more elegant way to do this. I feel like i'm playing wack-a-mole where my z-index property is the hammer and the onClick is the mole.
Currently, the nav items in the header nav aren't able to be clicked on because of their z-index. This fixes that by altering the z-index.

fix: zindex for search bar on headernav style

---

packages/gatsby-theme-carbon/src/components/GlobalSearch/GlobalSearch.module.scss

closes #1101 
Adds some media queries to handle search width at various viewports.

fix: adjust search container width to align with page contents

---

packages/example/package.json

The script for `dev:clean` is currently `yarn build && yarn clean` or something like this. 
If a user is utilizing `npm` as a package manager instead of yarn, or don't have yarn installed on their machine, they will continue to see error when running `npm run dev:clean`.
**New**
- Updated `package.json` avail scripts for npm users
**Changed**
- `dev:clean` points to `gatsby clean && gatsby develop -H 0.0.0.0`
**Removed**
- removed `yarn clean && yarn dev` from `dev:clean`

Fix: update package.json scripts for npm users

---

packages/example/src/pages/guides/configuration.mdx
packages/gatsby-theme-carbon/gatsby-config.js
packages/gatsby-theme-carbon/src/components/Header/Header.js
packages/gatsby-theme-carbon/src/components/Layout.js
packages/gatsby-theme-carbon/src/util/hooks/useMetadata.js

Closes #1131 
Adds `isSwitcherEnabled` theme option to control Switcher button/menu inclusion (defaults to `true`)

feat: add option to remove site switcher from header

---

packages/gatsby-theme-carbon/src/components/Switcher/Switcher.js

Closes #
N/A
**Changed**
- Updated link to Carbon for IBM.com website

chore(switcher): changing to new url for Carbon for IBM.com

---

packages/example/src/pages/guides/shadowing.mdx

The example path in the shadowing guide is incorrect. It does not match the component directories.
For reference this is the path to Header's index.js: https://github.com/carbon-design-system/gatsby-theme-carbon/blob/main/packages/gatsby-theme-carbon/src/components/Header/index.js
**Changed**
Path has been updated to match the component directories.

chore: Fix path in shadowing guide

---

packages/example/gatsby-config.js

Closes #
**New**
**Changed**
- changes theme_color to gray 100 / #161616. [theme_color](https://developer.mozilla.org/en-US/docs/Web/Manifest/theme_color) is used to tint the title bar in [Safari 15](https://css-tricks.com/safari-15-new-ui-theme-colors-and-a-css-tricks-cameo/) and [Android Chrome](https://developers.google.com/web/updates/2015/08/using-manifest-to-set-sitewide-theme-color)
Before:
After:
**Removed**

fix: changes theme_color to gray 100

---

packages/example/src/pages/guides/npm-scripts.mdx

Closes #
Update npm-scripts docs to match actual scripts
**New**
**Changed**
- npm script names in the guide
**Removed**
- scripts that are no longer available: `build:prefix`,`server:prefix`,`test:prefix`,`build:analyze`

Update npm-scripts docs to match actual scripts

---

packages/example/src/pages/components/MiniCard.mdx
packages/gatsby-theme-carbon/src/components/MiniCard/MiniCard.js

Closes #1159
This PR adds support for transferring props to Gatsby Links and anchors in the MiniCard component via the `linkProps` prop
**New**
- `linkProps` prop on `<MiniCard />`
**Changed**
- typo in MiniCard docs

feat(minicard): support transferring props to Gatsby Links and anchors

---

packages/gatsby-theme-carbon/src/styles/internal/_page.scss

Grid devtools overlay was 8px "off" at large breakpoint. 
Ensure text/components match up with grid overlay at large breakpoint

fix: update grid padding at large breakpoint

---

packages/gatsby-theme-carbon/src/components/Header/Header.module.scss

Closes #1168 
Switcher focus state was pulling in styles from the Carbon tooltip.
**New**
- Updated style override for Carbon button tooltip
**Removed**
- Old switcher style overrides no longer needed

fix: switcher button focus state

---

packages/example/src/pages/components/PageDescription.mdx

I've seen people trying to put too much into the page description. I think it is a sane content guidance to limit the text to one or two short sentences.
**Changed**
- Notes for the PageDescription component
As documented in #1194, I couldn't run `yarn ci-check` to check this change, but I ran `yarn && yarn build` instead.

docs: advice about the content for this component

---

README.md
packages/example/README.md
packages/example/src/pages/components/ImageGallery.mdx
packages/example/src/pages/components/MiniCard.mdx
packages/example/src/pages/components/ResourceCard.mdx
packages/example/src/pages/components/code-blocks.mdx
packages/example/src/pages/contributions.mdx
packages/gatsby-theme-carbon/gatsby-ssr.js
packages/gatsby-theme-carbon/src/styles/internal/_plex.scss

I found out late last year that most of the URLs in the code base still referenced the old homepage [https://gatsby-theme-carbon.now.sh](https://gatsby-theme-carbon.now.sh). The current and long-term URL is now [https://gatsby.carbondesignsystem.com/](https://gatsby.carbondesignsystem.com/), so I'm updating all references to the new URL. One of the advantages of that fix is that, as the fonts are loaded over the host too, the font loading will be faster as the redirect from `gatsby-theme-carbon.now.sh` to `gatsby-theme-carbon.vercel.app` will be avoided.
**Changed**
- References to the old URL.

fix: update the references to the new homepage

---

packages/example/src/pages/components/DoDontExample.mdx
packages/gatsby-theme-carbon/src/components/DoDontExample/DoDontExample.js
packages/gatsby-theme-carbon/src/components/DoDontExample/do-dont-example.scss

Closes #1188 
Check that the aspect ratio examples look correct.

feat: add additional aspect ratios for do dont

---

packages/example/src/pages/guides/configuration.mdx
packages/gatsby-theme-carbon/gatsby-config.js

Adds a new configuration option that allows user to include additional `gatsby-plugin-mdx` layouts.
**New**
- A new extraLayouts option is added to the theme's `gatsby-config.js`. It defaults to an empty object.
In a project using `gatsby-theme-carbon`, the user can add their own `gatsby-plugin-mdx` layout like so:
```
{
resolve: 'gatsby-theme-carbon',
options: {
navigationStyle: 'header',
mediumAccount: 'carbondesign',
isSwitcherEnabled: false,
titleType: 'prepend',
extraLayouts: {
posts: require.resolve('./src/layouts/postLayout.js')
},
...
```
where `posts` is defined in the same file with `gatsby-source-filesystem`.

feat: new config option to add default mdx layouts

---

packages/example/src/pages/components/Aside.mdx
packages/example/src/pages/components/DoDontExample.mdx
packages/example/src/pages/components/InlineNotification.mdx
packages/gatsby-theme-carbon/src/components/InlineNotification/InlineNotification.js
packages/gatsby-theme-carbon/src/components/InlineNotification/InlineNotification.module.scss

This re-implements `InlineNotification` for use in the editorial nature of the gatsby theme. It removes the `role='status'` from the notification, enabling interactive children elements. 
I've additionally added back a few links we removed in https://github.com/carbon-design-system/gatsby-theme-carbon/pull/1209 and reverted the changes to the InlineNotification page.
- Ensure inline notifications look the same between the example site deploy preview and the current production example website
- The `InlineNotification` page, and the Aside page show great examples to cross-reference.

fix(inlinenotification): re-enable inline links

---

packages/example/src/pages/guides/hosting.mdx

Corrects the getting started link here: https://gatsby-theme-carbon.vercel.app/guides/hosting#cirrus

fix(link): correct link to Cirrus getting started

---

packages/gatsby-theme-carbon/src/components/ExpressiveListContainer/ExpressiveListContainer.module.scss

Closes #1239
Sets `margin-top` to `0` for the first child of `.ExpressiveListContainer--text` and for the first adjacent element if `.ExpressiveListContainer--text` is empty (no `props.text` used, only `props.children`). The second rule makes sure that for example the video container on the documentation site is top-aligned when no text is used (example 2) but it keeps its top spacing when the text is populated (example 1).
**New**
- CSS rule for above logic in `ExpressiveListContainer.module.scss`

fix(expressive-list-container): remove margin-top from first content element

---

packages/gatsby-theme-carbon/src/styles/internal/_global.scss
packages/gatsby-theme-carbon/src/styles/internal/_grid.scss

ref https://github.com/carbon-design-system/carbon-website/issues/2884
Grid styles were being overwritten which was resulting in a busted StatusIndicator table
This PR moves grid styles into their own file and requires that file above the other mixins so those styles take precedence and get brought in properly 🤠 
Make sure it builds and compiles as expected 👍🏾

fix(grid): add _grid.scss and move over flex grid for precedence

---

packages/example/src/pages/demo/index.mdx
packages/gatsby-theme-carbon/package.json
packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss
yarn.lock

This fixes the bug blocking https://github.com/carbon-design-system/carbon-website/pull/2975
**Changed**
- Ensures that links placed as the second/third/fourth/etc sibling within a list item don't have unnecessary padding.
- Update sass version
- Formatting within the demo page
**Removed**
Demo page list section should render the new demo text with no extra vertical padding around links

fix(markdown): ensure links within lists do not have padding

---

.github/workflows/issue-triage.yml

Closes #1254 
**Changed**
- Add issue triage automation workflow, reuse the workflow from the Carbon monorepo

chore(project): add issue triage automation

---

packages/gatsby-theme-carbon/index.js

Adds MiniCard to be exported at the root. We had a report that 
```js
import { MiniCard } from "gatsby-theme-carbon";
``` 
was not working. Until this is published, workaround is 
```js
import { MiniCard } from "gatsby-theme-carbon/src/components/MiniCard";
```
**New**
- add MiniCard export to index.js

fix(minicard): export from root index.js

---

packages/gatsby-theme-carbon/src/components/FourOhFour/FourOhFour.module.scss

Closes #1309
Use correct tokens in 404 page theme
**Changed**
- FourOhFour.module.scss

Use color tokens in FourOhFour styles

---

packages/gatsby-theme-carbon/src/components/Switcher/Switcher.js
yarn.lock

Missed the `https://` 🙈
Sorry for round two.
**Changed**
- Fix link to Carbon for Cloud

fix: add https to carbon for cloud link

---

packages/example/src/pages/components/code-blocks.mdx
packages/example/src/pages/guides/configuration.mdx
packages/gatsby-theme-carbon/gatsby-config.mjs
packages/gatsby-theme-carbon/package.json
packages/gatsby-theme-carbon/src/components/Code/Code.js
packages/gatsby-theme-carbon/src/components/Code/Code.module.scss
yarn.lock

This PR fixes the following - 
- Show more button in Code blocks
- Added a prop to enable/disable Show more button in Code blocls
- Added text wrap to avoid horizontal scroll
- Added a new package that is traversing hast and adding a new property named metaData which is being passed as a prop
Should close - https://github.com/carbon-design-system/gatsby-theme-carbon/issues/868

Fix: code blocks in mdx + issues/868

---

packages/example/src/pages/guides/v2-migration.mdx
packages/gatsby-theme-carbon/src/components/Code/Code.module.scss

Ref #1439
Fix copy icon color token

fix: copy button color token

---

packages/example/src/pages/components/code-blocks.mdx
packages/gatsby-theme-carbon/src/components/Code/Code.js

This PR aims at removing the regression introduced by a new prop introduced in Code blocks.
Changed the value of `hideCode` to `true` so that the blocks show a "Show more" button in all code blocks having more than 9 lines.

Fix regression in code blocks

---

packages/gatsby-theme-carbon/src/components/LeftNav/LeftNavTree.js
yarn.lock

Closes #1504 
When on a tabbed page, highlight the matching nav item in the tree navigation.
**Changed**
- packages/gatsby-theme-carbon/src/components/LeftNav/LeftNavTree.js

fix(leftnavtree): highlight nav item for tabbed pages

---

packages/gatsby-theme-carbon/src/components/LeftNav/LeftNavTree.js
yarn.lock

fixes issue where treenav isn't responding correctly to url paths in carbon-for-products-website.
**Changed**
- Removed the pathPrefix from the location.path value before comparing it with the menu item path.

fix(leftnavtree): menu is not activated when the URL has pathprefix

---

packages/example/src/pages/components/PageDescription.mdx
packages/example/src/pages/components/ResourceCard.mdx
packages/gatsby-theme-carbon/src/components/PageDescription/PageDescription.module.scss
packages/gatsby-theme-carbon/src/components/ResourceCard/resource-card.scss
yarn.lock

Related issue https://github.com/carbon-design-system/carbon-website/pull/4258
|  | |
| -------- | ------- |
| ![image](https://github.com/user-attachments/assets/fff2d36b-e53f-411b-96a7-a34642af1c6d)  | ![image](https://github.com/user-attachments/assets/eb14e723-0c46-4cae-b3af-919213f89b5e)    
**New**
- Add styles for spacing between multiple children in Resource Cards
- Add styles for optional Tag inside of PageDescription
https://deploy-preview-1513--gatsby-theme-carbon.netlify.app/components/ResourceCard/#with-tag
https://deploy-preview-1513--gatsby-theme-carbon.netlify.app/components/PageDescription/

feat: add Tag styles for PageDescription and ResourceCard

---

packages/example/src/data/nav-items.yaml
packages/example/src/pages/demo-level-1/demo-level-2/demo-page-2/tab-1.mdx
packages/example/src/pages/demo-level-1/demo-level-2/demo-page-2/tab-2.mdx
packages/example/src/pages/demo-level-1/demo-level-2/demo-page-3.mdx
packages/gatsby-theme-carbon/src/components/LeftNav/LeftNavTree.js
yarn.lock

Closes #1511 
In Level 2 pages, tabs highlight the last menu item within the respective Level 2 section
**Changed**
- Revised the logic for identifying the active menu item for the tabbed page.
- Included an example for the tabbed page in Level 2.

fix(leftnavtree): highlight nav menu item for tabbed pages in level2

---

packages/gatsby-theme-carbon/src/components/PageDescription/PageDescription.module.scss
yarn.lock

Closes #1517
**Changed**
- fix spacing for PageDescription with tag
https://gatsby-theme-carbon-git-fork-alison-dacea3-carbon-design-system.vercel.app/components/PageDescription/

fix: page description with tag spacing

---

packages/gatsby-theme-carbon/gatsby-ssr.js
packages/gatsby-theme-carbon/src/styles/internal/_plex.scss
yarn.lock

Based on a recent edge traffic report from Vercel, there has been a massive increase in traffic due to the hosting of fonts directly on Vercel. This is a pivot to move hosting to IBM Akamai instead, which can handle spikes in traffic without an incurred cost to our team.
**Changed**
- Changes font domain from `gatsby.carbondesignsystem.com` to `1.www.s81c.com`

chore(fonts): update fonts to IBM Akamai urls

---

packages/gatsby-theme-carbon/src/components/GlobalSearch/GlobalSearch.js
packages/gatsby-theme-carbon/src/components/GlobalSearch/Menu.js
packages/gatsby-theme-carbon/src/util/convertFilePathToUrl.js
yarn.lock

Closes #1524
Fix so enter key 
- moved convertFilePathToUrl out of Menu and into utilites folder
- convert the file path to url when hitting the enter key for GlobalSearch
Search for something that has results and hit enter, it should navigate the first item selected in the results list, or the item you have navigated to by keyboard.

fix(search): keyboard support for enter key

---

.github/workflows/release.yml
package.json
packages/gatsby-theme-carbon/package.json
yarn.lock

Closes https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1369
Update to publish with provenance
https://docs.npmjs.com/generating-provenance-statements
mirrored what was done for core Carbon https://github.com/carbon-design-system/carbon/pull/14344
**New**
- add provenance: true to publishConfig in package.json files
**Changed**
- update publish workflows to have proper permissions per the npm docs
**Removed**
- remove registry from package.json, should not be needed as its the default

chore(npm): publish packages with provenance

---

.github/workflows/validate-and-build.yaml
yarn.lock

Update the ubuntu version to `ubuntu-latest` as the [`Ubuntu 20.04` runner image is no longer supported](https://github.com/actions/runner-images/issues/11101).
**Changed**
- update the validate-and-build GitHub Action workflow to use `ubuntu-latest`

chore: update validate workflow ubuntu version
